### ISSUE TITLE
PSNR: 23.6637, 23.5029

### ISSUE THREAD

**Issue by xu3385** [AlexZou14/CVHSSR#3]
您好，我用提供的CVHSSR_Sx4.pth和CVHSSR_Tx4.pth在Flickr1024测试集上做了测试，PSNR结果只有23.6637dB.和23.5029dB。这与论文中的结果不符。请问提供pre-trained model是否提供错了，可以提供PSNR=24.08dB和23.89dB的checkpoint吗？

**Comment by AlexZou14** [comment]
我之前发现这个问题了，权重没更新上去，现在我重新更新了权重，你再试试

**Comment by xu3385** [comment]
我这边测的和之前没有区别。

**Comment by AlexZou14** [comment]
我这边测试没错啊，你确定用的是我重新上传的权重嘛

**Comment by xu3385** [comment]
可以了，是我数据集的准备出了点问题。感谢回复！
